# ==========================================
# LOGGING
# ==========================================
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# ==========================================
# HARDWARE DRIVERS
# ==========================================
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SPI=y
CONFIG_REGULATOR=y
CONFIG_MFD=y

# ==========================================
# NETWORKING & WI-FI CORE
# ==========================================
CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_IPV4=y
CONFIG_WIFI=y
CONFIG_WIFI_NRF70=y

# ==========================================
# MEMORY SIZING
# ==========================================
CONFIG_HEAP_MEM_POOL_SIZE=40000
CONFIG_NRF_WIFI_CTRL_HEAP_SIZE=15000
CONFIG_NRF_WIFI_DATA_HEAP_SIZE=10000
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

# Wi fi management
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_WIFI_LOG_LEVEL_INF=y

# Enable a random MAC address
CONFIG_WIFI_RANDOM_MAC_ADDRESS=y

# Enable a hardware entropy generator 
CONFIG_ENTROPY_GENERATOR=y
