/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 12.07.2026 17:15:02

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1456;
#else
constexpr int kTensorArenaSize = 432;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,88 } };
const TfArray<1, float> quant0_scale = { 1, { 0.059003770351409912, } };
const TfArray<1, int> quant0_zero = { 1, { -5 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { -368, 368, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0001591311302036047, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[2*10] = { 
  68, -116, 71, 108, 127, -91, -47, -122, 4, 89, 
  80, 25, -20, -22, -99, 9, -120, 69, -91, 40, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 2,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0053919549100100994, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 260, 572, -272, -383, -339, 520, -376, 592, -453, -377, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00010110578296007589, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  44, -74, -60, 17, 107, 21, 116, -101, -2, -49, 21, 20, 72, 122, 61, -79, 5, -23, -69, 26, 
  -56, -94, 74, 78, 73, -38, -34, -92, -79, 20, -40, -51, 67, 26, 77, 108, -51, 39, -43, -15, 
  -21, -105, -3, 101, -54, -59, -42, 19, -46, -10, 28, 47, -20, -86, -16, -77, 85, -97, -100, -85, 
  61, 2, 90, -7, -79, 87, -66, -48, -35, 81, 94, 46, -69, -90, -1, -56, -22, -56, 110, 75, 
  -34, 50, -96, -53, -98, 82, -44, 25, -98, 68, 84, 56, -15, 47, 24, -104, -41, 99, 77, 50, 
  -80, 87, -55, 66, -15, -120, 7, 90, -105, -44, 87, 66, -38, 75, -17, -52, -25, 73, -58, 16, 
  94, 36, -63, -86, 67, 87, 2, -36, -34, 10, 57, 39, -66, -43, 9, -27, 65, -9, -8, -43, 
  -19, 108, 49, 77, 4, 77, 102, -114, 127, -36, -50, 116, 68, -26, -105, 66, 85, 8, 9, 97, 
  56, 28, 42, 29, 74, 28, -120, -38, -39, 4, 88, 16, -14, -116, -48, 83, -93, 62, -55, -42, 
  47, -82, -21, -14, 67, 110, -28, 7, 70, -84, -68, 46, -67, -54, 54, -30, -10, 89, 8, 69, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0038030669093132019, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -322, 379, 124, 486, 269, -120, 352, 3, 271, -194, -267, -12, 248, 193, 36, 412, 291, -176, -209, 177, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00013454923464450985, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*88] = { 
  -15, -10, -31, 92, 39, 40, 21, -76, 34, -90, -7, 28, -80, -55, -39, 76, 8, 75, -39, -61, 91, -30, 101, 21, -86, 68, -49, -34, -76, -88, 16, 14, 56, -78, -79, 35, -58, 83, 1, -56, 30, -8, -84, -44, -99, 64, -40, 94, -47, -70, -5, -80, 56, -7, -71, 69, 79, 72, 89, 57, 45, -47, 13, -62, -6, -55, 19, 49, 94, 3, 8, -95, -78, -29, -15, -61, 75, 45, -21, 102, 47, 14, -31, 46, -1, 16, -84, 0, 
  -74, 3, 99, -4, -50, 37, 47, 35, 52, 99, -65, 47, 27, -4, 88, -36, 104, 36, 82, -40, -6, -12, 70, -18, 50, 51, -27, 52, 1, -62, 0, 117, 88, 98, 47, -24, -64, -31, 6, -68, -21, -79, 127, 87, 82, -7, 67, -61, -10, -8, -100, -39, -24, -65, -25, -126, -71, 78, 85, -94, -39, 90, -24, -32, -36, 7, 80, -96, 41, -53, 119, -42, 81, -18, -7, 106, -20, -61, -12, 87, -21, -106, -46, -28, 27, 27, -47, -102, 
  81, -15, -80, -82, 33, -41, 70, 109, 96, 4, -69, 29, -81, 41, -45, 74, 53, 54, -7, 53, 103, -88, 43, -72, 17, -18, 92, 41, -45, -73, -36, 53, 36, -61, -4, -40, -97, 3, 64, -68, 62, 50, -84, -8, 55, -33, -62, -70, 51, -13, 54, -18, -14, 3, 49, -99, 26, 22, 25, -41, 85, -23, -13, 39, -25, 68, 30, -49, -23, -46, 15, -80, 27, 75, -28, -75, -77, 68, -50, -70, 30, -64, 29, -21, -9, 14, -40, -15, 
  -65, 55, -42, 57, -19, 71, -5, 118, 48, -80, 84, 88, 50, 47, 61, -17, -59, -48, 25, 74, -68, 40, -86, -43, 52, 47, -84, 47, 103, 60, -38, 60, 85, -48, 42, 24, 104, -120, -2, 48, -80, 45, 19, 98, 116, -56, -5, -62, 45, 62, -51, -27, -44, -126, 31, -98, -66, -107, -35, -14, 81, 47, 96, 83, -61, -101, 48, -97, -75, -114, 80, -38, -36, -67, 10, 46, -24, 99, 53, 83, 3, 50, 69, -51, -41, -80, -34, -60, 
  87, 6, 7, -65, -85, -68, 88, -22, -62, 75, -19, 34, -74, -39, -63, 45, 73, 71, -10, -21, -15, 97, -31, -8, -30, 13, 66, 63, -93, -88, 45, -71, 84, -71, -17, -46, -31, -90, 23, 63, -6, 30, -86, -30, 69, -70, 79, 60, -5, 83, 83, 78, -78, -22, -14, 85, 77, 65, 82, 47, -95, -73, 87, 112, 13, 63, -37, 106, -94, -33, -68, 32, 84, 33, 34, 57, -23, -32, -41, -49, 66, -106, 33, -90, 14, -72, 11, -75, 
  -51, 73, 4, 11, -16, -101, -3, 79, -39, 6, -109, -53, -84, 54, -5, -7, -118, 36, -14, -11, -81, -88, 5, -59, 68, -35, 31, 3, -52, 106, -31, -14, 91, -66, 24, -101, 71, -62, 43, 87, 55, 39, -80, -48, -5, -106, -69, -77, -7, 49, 86, -12, 38, -39, 53, 75, 14, -13, 46, 22, 43, -115, 61, -97, -26, -6, -44, 76, 92, 66, 70, -62, 43, -63, -86, -82, -25, -16, 59, 10, -69, 48, -57, 106, 14, -60, 50, 1, 
  66, -42, -35, -65, -75, -88, -25, 74, -47, 18, 2, 2, 5, 45, 58, -6, -23, -58, 89, 91, -44, 18, -61, 69, -41, -7, 93, -101, 95, 37, 83, -89, -1, -8, -90, 62, -87, 29, -97, 89, -13, 10, 4, 17, -37, -75, 95, -54, -11, -23, -59, 75, -98, 54, 36, -23, 27, 92, 70, -43, -74, 21, 79, -60, 49, 27, -93, 65, -74, -74, 36, 109, -11, 45, 20, 73, 51, 70, 52, -55, 64, 52, 8, 13, -76, -19, 44, 8, 
  64, -98, 25, 99, 102, 16, 16, 32, -22, 72, -34, 84, -36, 48, -80, -103, -48, -46, -57, 83, 76, -58, -40, -14, -33, 86, -29, 37, -105, -24, 9, 90, 30, -96, -34, -100, -30, 32, 76, -31, -25, 35, 94, 83, 22, -9, 28, -94, -66, 44, -67, -26, -18, 18, -23, -55, -104, 73, 59, -90, -57, -47, 44, -72, 44, 18, 13, -52, -50, 115, -78, 0, -36, 53, 11, 4, -50, 56, -47, 52, 103, -99, 68, 9, 43, -97, 58, 57, 
  74, 90, 61, -29, -102, 77, 0, -68, -9, -6, 15, 73, 53, -55, 35, -35, 56, -56, 87, 35, 103, 69, 82, 48, 67, 71, 59, -27, 101, -102, 51, -87, -24, 6, -95, -21, -86, 71, -84, -6, -39, -69, -75, -37, -75, 46, -45, -4, -61, 32, -81, -120, 82, -85, 61, 33, 32, 37, -18, -49, 51, -9, 96, -41, 1, -92, 93, 79, 54, -70, -23, -17, 34, -89, -47, -77, -66, -60, -59, 79, -57, -66, -70, -66, 70, 38, -21, 20, 
  -104, 46, -97, 3, -48, 47, -102, 1, -47, -111, -93, -78, -100, -11, -84, 70, -29, 64, 83, -78, -21, 58, 33, 98, 105, 72, 15, 47, -13, 34, -64, -31, -61, -10, 64, 22, 63, 82, -6, 19, 18, 52, -67, 7, -60, -105, 73, 35, 82, -73, 45, 104, -90, -90, -67, 28, 39, 18, -98, 40, -78, -70, -75, 66, 3, -24, -98, -29, -63, 60, -83, 49, 69, 6, -5, -91, 83, -25, -113, 78, 58, 105, -89, -41, -54, 68, -52, -38, 
  83, 27, 36, -97, -73, -48, 56, 12, 0, 34, -74, 31, 23, -65, 34, -61, -14, -4, 44, 15, -84, 45, -80, 90, 96, -9, -35, -17, 60, 80, -100, -93, -71, -26, 111, 77, -32, -65, -64, 44, 45, 0, -7, -41, -47, 56, 11, -103, 71, 36, -44, -48, -4, 9, 65, 102, -82, -29, 31, -17, 35, 26, 69, 59, 19, -88, -80, 57, 45, 43, 64, 1, -37, -51, 7, 83, 28, -50, 42, 119, -25, -53, 42, -54, -30, 56, -22, 41, 
  -4, 31, 87, -46, -93, -76, 117, -46, 77, -24, 88, 94, 72, 84, -25, 59, -41, -51, 75, 19, -11, -18, 83, 3, 34, 40, 66, 38, 116, 45, -6, -17, -5, -35, 14, -8, -61, 14, 15, 43, 45, 62, 103, -31, -67, -22, 13, 59, -105, -1, -84, 54, 18, 20, 91, 55, 61, -22, 7, -84, 60, 70, 11, -41, 67, 64, 68, -22, -31, -30, -73, -4, -70, -66, 66, 44, 55, 92, 51, 27, 55, 102, -81, -59, -103, -77, -79, 32, 
  -28, -93, 14, -43, 50, -75, -52, -93, -92, 57, -21, -88, 16, 37, -15, 92, 32, -42, 72, -14, 51, 75, -78, 60, 46, -36, 9, -70, 102, -26, -30, 21, -116, 105, 65, 75, 91, -75, -98, -71, 1, 1, -66, -35, -86, -36, 84, 72, -16, 115, 73, -107, -121, 2, -73, -116, -50, 31, -11, 35, -48, -60, -72, 83, 23, 18, 58, 31, 2, 52, 18, -34, 64, 60, 14, -88, -30, 91, -79, -105, -1, 28, 86, 48, 76, 99, -115, -80, 
  35, -113, -55, -13, 80, 110, -78, 104, -9, 31, 25, 34, 100, 19, -5, -73, -92, -22, -94, -28, -76, -71, -18, -34, -45, -104, -74, 76, -8, 9, 39, -107, -89, -89, -3, 34, 59, -2, 86, -26, 98, 41, 93, -65, 97, -47, -13, 69, 111, 55, 44, 47, -80, -50, 99, -47, 32, 63, 47, -23, -10, -26, -13, -72, 73, 77, 82, 79, 21, 83, -72, -14, 74, -22, 41, -66, -51, -44, 52, -69, -50, 37, -33, -45, 42, 24, 63, 77, 
  76, -73, -57, 35, 23, -78, -61, 31, 57, 19, 87, -117, -85, 115, -120, -47, -108, 26, 73, -98, 76, 85, -35, 66, -103, -69, -3, -66, 69, -26, 97, -60, -35, 54, -13, -66, -84, 30, 91, -89, -107, 92, -111, 50, -31, 64, -28, -78, -100, -52, -14, 47, 35, -16, -70, -55, 73, -19, 85, -45, 21, 26, -75, 84, 11, 81, 77, 52, -13, 71, -8, -78, 73, -29, 104, 32, -57, 26, -6, 7, 52, 9, -79, -31, 38, -84, 96, 26, 
  21, 80, -73, -97, -102, 37, -11, 32, 35, 35, -10, 41, -71, 31, 69, 91, 36, 49, 29, 68, -100, 95, -98, 32, 8, -12, -38, -57, -3, -51, 41, -27, -53, 61, -11, 22, 10, -106, 14, 80, 48, -64, 48, -60, 90, -47, -97, -17, -81, 78, 60, -26, 54, 70, 54, -76, 110, 24, -89, 91, -7, -54, 13, -37, 28, 24, -3, -79, 18, 47, -67, 95, 98, 103, 33, 81, -44, 18, 92, 16, -94, -82, 2, 78, 82, 96, -12, 30, 
  20, -70, -31, -18, 70, -11, -25, -74, 48, -83, -90, -26, 36, 34, -17, 50, -62, -55, 32, -19, -87, -54, 25, -48, 34, -38, -25, 61, -58, 80, 53, 12, 71, -57, -42, -38, 38, -102, -62, -11, 11, -29, 32, 94, 5, -66, 76, -89, -17, -44, 12, -30, -37, -92, -19, -109, 4, -32, 71, -77, -81, 102, -56, 11, -86, 37, -10, -48, -12, 79, -66, -3, -34, 83, 63, 67, -37, 32, -51, 6, 6, 77, -106, -52, -25, 89, -16, -84, 
  -35, 57, 88, 84, 92, -50, -53, 70, 40, -27, -45, 86, -26, 82, -90, -26, -91, 25, 109, -73, 55, -39, -67, 101, -53, -80, -49, 47, -20, -53, -26, -81, 20, 18, 8, 89, 102, -51, 79, -82, -93, -20, 89, -47, 11, -71, 20, 81, -78, 38, -59, -51, 104, 62, 20, -62, 60, -86, -31, -38, 48, -99, 51, 81, -29, 54, -11, 2, 29, -13, 59, -54, 44, 99, 65, 8, -94, -65, 77, -69, -71, -84, -82, 38, 71, 96, -25, 38, 
  -105, -16, 51, -88, 66, -8, -80, -13, 11, -50, -105, -53, -89, -56, -95, -48, -10, -57, -43, 25, -53, 80, -38, 80, -42, -90, 10, -13, -103, -67, 37, -44, -53, -99, 99, 62, 33, -59, -65, -24, -73, 31, -75, 32, -16, -23, 111, 17, -83, -85, -4, -75, 60, -46, 59, -61, -86, -50, -30, 86, -18, -68, -70, 69, 43, -51, 91, -81, 2, 109, 44, 39, 55, -39, -82, 16, 81, 29, -43, 48, 44, 56, 92, 17, 71, 21, 107, 25, 
  9, 77, 7, -55, -26, -27, 31, -14, 71, 63, -93, 74, 77, -14, 11, -28, 12, -89, -64, 36, -43, -82, 79, -89, -15, -5, -62, -56, 50, 86, -63, 28, 87, -59, -9, 22, -82, 8, -6, -27, -50, -82, 43, 63, 11, -77, -97, 31, -15, 4, 22, 30, -102, 18, 38, -69, 61, -79, -66, 92, -83, 72, -80, 24, -85, -16, -23, -74, -81, -67, -88, 72, -25, -9, -24, 38, -100, -106, -99, -57, 67, -19, -1, -97, -21, 53, 81, -25, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,88 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0022803498432040215, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.026585329324007034, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.029512697830796242, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,2 } };
const TfArray<1, float> quant9_scale = { 1, { 0.041458047926425934, } };
const TfArray<1, int> quant9_zero = { 1, { -23 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 88, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1760, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 96), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1022358_14_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022358_14_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022358_14_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022358_14_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022358_14_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
