/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 23.07.2026 21:21:32

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1456;
#else
constexpr int kTensorArenaSize = 432;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,89 } };
const TfArray<1, float> quant0_scale = { 1, { 0.04373534768819809, } };
const TfArray<1, int> quant0_zero = { 1, { -30 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { -263, 263, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00016027943638619035, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[2*10] = { 
  57, -117, 80, 105, 127, -86, -41, -114, 5, 97, 
  80, 33, -32, -25, -101, 9, -115, 64, -87, 23, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 2,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0057950210757553577, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 518, 792, 341, -158, -4, 579, -221, 511, -333, 366, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 9.7339223430026323e-05, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  27, -41, -36, 35, 109, 21, 127, -105, -8, -38, 23, 17, 83, 119, 42, -45, 15, -1, -69, 26, 
  -47, -76, 74, 78, 67, -25, -21, -95, -65, 34, -36, -56, 75, 39, 61, 103, -32, 47, -36, -5, 
  -15, -100, 13, 95, -30, -50, -31, 30, -31, -7, 26, 56, -25, -80, -10, -69, 81, -79, -81, -73, 
  57, -1, 78, 2, -60, 78, -63, -25, -12, 63, 84, 55, -71, -87, -3, -52, -29, -52, 106, 72, 
  -27, 41, -96, -42, -67, 74, -42, 39, -74, 62, 76, 59, -16, 51, 28, -90, -39, 84, 84, 49, 
  -70, 85, -52, 58, -27, -110, 11, 57, -108, -42, 79, 44, -29, 64, -26, -41, -25, 66, -68, 18, 
  87, 26, -60, -76, 69, 79, -1, -16, -23, 2, 50, 40, -64, -34, 9, -25, 55, -16, -4, -41, 
  -16, 101, 52, 65, -5, 71, 97, -112, 94, -20, -45, 93, 72, -17, -93, 65, 82, 17, -1, 84, 
  56, 25, 42, 34, 76, 38, -108, -10, -27, 5, 79, 26, -16, -100, -29, 70, -85, 55, -34, -38, 
  54, -76, -10, 2, 76, 101, -28, 25, 81, -75, -57, 54, -62, -45, 55, -24, -12, 73, 19, 68, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0042818007059395313, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -224, 333, 430, 709, -263, 428, 575, 539, -36, 177, -249, 614, 226, 597, 414, 645, 192, 208, 420, 626, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00011155930405948311, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*89] = { 
  -12, -1, -7, 73, 34, 32, 29, -50, 22, -56, 10, 49, -86, -46, -33, 94, 43, 42, -36, -52, 100, -33, 66, 37, -64, 78, -69, -34, -73, -71, 35, 11, 44, -76, -69, 20, -81, 79, 0, -45, 41, -2, -74, -21, -78, 63, -35, 81, -45, -51, -19, -75, 41, -10, -91, 61, 75, 66, 96, 43, 41, -39, 19, -61, -26, -55, 6, 38, 64, 1, 6, -86, -64, -39, -8, -59, 69, 55, -35, 89, 38, 12, -30, 47, 1, 21, -72, 12, -49, 
  -68, -20, 58, 12, -50, 47, 25, 17, 30, 78, -66, 32, 6, -1, 85, -41, 78, 50, 64, -27, -33, -23, 48, -33, 33, 28, -17, 50, -4, -50, 0, 85, 55, 112, 57, -14, -50, -10, 24, -42, -41, -67, 125, 62, 64, -19, 32, -30, 8, 12, -62, -22, -6, -45, 17, -127, -63, 97, 102, -81, -43, 84, -28, 2, -13, 8, 75, -84, 43, -40, 115, -20, 85, -15, -13, 99, -13, -62, 11, 81, -10, -91, -42, -34, 3, -5, -60, -105, -20, 
  76, -2, -70, -52, 34, -38, 46, 89, 92, -26, -84, -3, -64, 37, -32, 59, 26, 71, -5, 40, 84, -98, 58, -95, -11, -47, 96, 30, -32, -74, -46, 66, 33, -47, -9, -28, -39, 2, 60, -61, 37, 40, -77, 0, 47, -32, -63, -61, 41, -45, 32, -7, -2, 12, 55, -76, 20, -8, 6, -20, 78, -30, -16, 0, -19, 55, 28, -48, -13, -35, 17, -95, 15, 89, -24, -76, -87, 21, -42, -77, 18, -72, 35, -28, -12, 31, -49, -34, -96, 
  -53, 37, -56, 61, -26, 73, -14, 95, 59, -91, 59, 58, 30, 38, 63, -33, -75, -33, 10, 73, -73, 36, -76, -54, 36, 26, -84, 30, 97, 54, -48, 51, 59, -24, 43, 19, 109, -104, 0, 46, -78, 34, 23, 81, 106, -58, -22, -43, 50, 32, -52, -21, -35, -110, 12, -90, -59, -96, -36, -1, 69, 43, 73, 67, -62, -99, 34, -96, -62, -99, 71, -50, -37, -53, 6, 44, -31, 78, 48, 69, 0, 39, 69, -46, -35, -58, -32, -63, 36, 
  82, 17, 17, -48, -70, -70, 68, -15, -45, 43, -35, 6, -73, -34, -53, 47, 53, 69, -8, -27, -19, 66, -32, -23, -36, -5, 47, 62, -78, -71, 44, -52, 70, -58, -35, -51, -11, -87, 14, 49, 18, 33, -76, -19, 68, -56, 58, 61, -22, 57, 62, 68, -69, -21, -23, 91, 63, 61, 70, 61, -78, -70, 72, 81, -7, 39, -49, 77, -88, -16, -73, 26, 72, 47, 38, 44, -35, -31, -31, -48, 57, -99, 48, -69, 26, -30, 5, -94, 48, 
  -41, 81, 27, -12, -21, -80, 16, 93, -50, 35, -74, -18, -91, 54, 1, 21, -57, 12, -20, 6, -57, -72, -15, -26, 83, -4, -5, -5, -59, 92, -15, -12, 85, -71, 10, -94, 30, -52, 31, 81, 67, 49, -70, -29, 8, -80, -53, -73, -11, 63, 70, -22, 17, -46, 21, 60, 18, 1, 64, 3, 33, -94, 63, -87, -19, 3, -37, 76, 71, 59, 69, -47, 50, -73, -81, -68, -13, -9, 54, 14, -61, 48, -30, 89, 20, -43, 52, 18, 117, 
  64, -32, -42, -52, -72, -73, -33, 57, -49, -7, -21, -21, 14, 32, 54, -19, -40, -41, 73, 81, -49, 4, -43, 41, -55, -27, 112, -97, 90, 18, 54, -85, -16, 5, -59, 64, -56, 45, -67, 99, -8, 3, 12, 2, -43, -85, 68, -33, 4, -34, -45, 75, -80, 56, 58, -32, 24, 87, 63, -41, -73, 24, 70, -47, 47, 27, -79, 61, -58, -66, 31, 87, -16, 38, 12, 69, 51, 59, 47, -47, 59, 49, -3, 8, -74, -27, 32, -3, -64, 
  51, -99, 20, 77, 100, 1, 24, 38, -15, 85, -6, 96, -17, 40, -76, -82, -24, -52, -38, 67, 75, -39, -33, 6, -12, 95, -27, 28, -103, -5, 25, 73, 43, -106, -38, -74, -55, 19, 53, -37, -22, 35, 77, 77, 19, 0, 45, -96, -64, 59, -49, -29, -22, 9, -50, -44, -90, 70, 54, -92, -40, -45, 50, -59, 27, 18, 9, -44, -52, 87, -76, 20, -26, 34, 19, 1, -32, 61, -69, 58, 98, -76, 39, 18, 46, -83, 65, 71, 83, 
  62, 67, 33, -8, -88, 69, -21, -73, -27, -29, -10, 41, 54, -48, 28, -51, 24, -31, 79, 24, 69, 45, 70, 21, 40, 42, 70, -22, 87, -90, 41, -79, -27, 11, -70, -16, -56, 78, -55, 10, -50, -62, -67, -43, -80, 30, -48, 1, -45, 17, -81, -94, 88, -62, 62, 24, 21, 56, 5, -41, 42, -8, 81, -26, 19, -82, 84, 70, 68, -56, -25, -23, 25, -75, -43, -69, -53, -51, -36, 68, -54, -62, -69, -58, 52, -1, -30, 8, 28, 
  -89, 36, -85, -7, -41, 42, -79, 7, -64, -83, -72, -53, -97, -16, -72, 70, -10, 48, 74, -66, -12, 75, 27, 98, 102, 75, -1, 40, -17, 42, -41, -12, -51, -19, 50, 19, 42, 54, -28, -1, 12, 51, -61, 9, -52, -77, 75, 22, 64, -68, 35, 70, -103, -102, -67, 22, 42, 11, -85, 34, -71, -60, -63, 65, 2, -22, -89, -26, -77, 44, -72, 48, 65, 1, -6, -79, 75, -19, -104, 75, 54, 100, -58, -40, -40, 77, -38, -24, 69, 
  72, 35, 54, -80, -56, -52, 48, 26, -9, 36, -58, 33, 9, -55, 28, -42, 4, -6, 47, 9, -69, 49, -73, 87, 91, -1, -52, -13, 49, 76, -73, -74, -59, -31, 89, 72, -41, -65, -69, 32, 27, 5, -12, -17, -39, 59, 20, -97, 50, 42, -49, -43, -7, 8, 52, 99, -74, -37, 19, -12, 36, 20, 62, 53, 17, -79, -73, 50, 31, 39, 58, 7, -31, -40, 10, 70, 21, -46, 30, 102, -29, -51, 33, -50, -18, 80, -11, 44, -14, 
  -30, 49, 98, -38, -70, -78, 100, -43, 60, -4, 94, 101, 68, 93, -54, 62, -16, -43, 85, 14, -9, -17, 93, 24, 45, 56, 59, 60, 83, 41, -1, -31, 12, -42, 25, -27, -75, 23, 22, 48, 53, 74, 68, -20, -58, -28, 28, 39, -79, 17, -67, 63, 28, 32, 74, 68, 41, -19, 10, -74, 71, 45, 0, -21, 74, 52, 52, -25, -37, -14, -78, 4, -59, -59, 71, 25, 39, 90, 42, 24, 48, 91, -72, -44, -76, -106, -38, 75, 2, 
  -25, -92, -3, -20, 38, -53, -60, -93, -54, 31, -31, -97, 8, 40, -9, 51, -4, -8, 58, -4, 14, 34, -74, 35, 26, -51, 11, -63, 89, -32, -48, 34, -100, 102, 38, 69, 103, -70, -83, -67, -6, 7, -58, -49, -87, -29, 69, 73, -26, 101, 67, -92, -100, 6, -44, -102, -50, 27, -23, 54, -33, -59, -84, 37, 22, 11, 49, 22, 11, 55, 19, -42, 51, 74, 19, -84, -43, 40, -52, -95, 0, 23, 91, 36, 67, 94, -110, -84, -14, 
  40, -109, -72, -10, 68, 102, -74, 94, -5, 12, 4, 15, 73, 2, 2, -92, -118, -14, -83, -26, -82, -69, 7, -51, -60, -112, -29, 55, -4, -2, 15, -95, -77, -79, -3, 28, 59, 1, 81, -21, 87, 34, 87, -82, 61, -45, -14, 60, 90, 48, 33, 40, -66, -46, 100, -53, 32, 56, 30, -9, -4, -28, -27, -71, 42, 56, 61, 57, 2, 69, -60, -22, 56, 0, 45, -66, -62, -49, 55, -70, -54, 23, -18, -55, 42, 38, 50, 53, -14, 
  70, -56, -31, -1, 15, -68, -22, 34, 48, 49, 108, -72, -70, 97, -103, -23, -70, -6, 62, -73, 97, 87, -34, 85, -69, -36, -36, -67, 64, -27, 91, -58, -28, 45, -16, -62, -100, 17, 67, -88, -88, 79, -100, 48, -26, 55, -17, -72, -88, -28, -26, 39, 28, -17, -89, -51, 72, -21, 71, -52, 23, 24, -55, 63, -7, 80, 71, 55, -25, 54, -7, -57, 71, -39, 93, 29, -43, 25, -25, 17, 53, 19, -63, -26, 42, -57, 95, 33, -51, 
  22, 81, -63, -86, -104, 44, -13, 23, 39, 20, -16, 25, -38, 20, 65, 67, 25, 45, 14, 69, -92, 82, -86, 22, 4, -17, -34, -54, 2, -55, 23, -43, -47, 64, 6, 19, 18, -75, 29, 90, 50, -67, 50, -48, 84, -64, -101, -7, -55, 49, 47, -11, 60, 74, 55, -79, 96, 50, -52, 83, -11, -46, 10, -27, 17, 25, 0, -67, -11, 46, -60, 97, 95, 83, 24, 78, -39, 6, 75, 16, -82, -71, -3, 67, 68, 49, -15, 26, 28, 
  15, -58, -33, 9, 70, -13, -42, -69, 40, -98, -94, -47, 17, 32, -17, 18, -93, -26, 37, -27, -97, -59, 26, -58, 22, -49, -12, 54, -53, 68, 37, 13, 58, -38, -34, -33, 52, -85, -40, -3, -5, -24, 25, 83, 7, -80, 53, -68, -5, -53, 0, -11, -11, -66, -7, -92, -7, -21, 57, -59, -62, 86, -57, 8, -54, 40, 7, -36, 0, 80, -61, -8, -30, 84, 60, 57, -44, 24, -46, 3, 8, 67, -100, -46, -28, 58, -20, -82, 62, 
  -17, 42, 75, 70, 75, -36, -40, 84, 25, -18, -38, 83, -48, 55, -66, -34, -71, 30, 92, -55, 46, -30, -75, 90, -49, -71, -67, 7, -20, -51, -15, -56, 15, 10, -10, 83, 59, -60, 54, -88, -84, -9, 81, -27, 21, -42, 23, 74, -85, 52, -43, -59, 79, 42, 15, -54, 58, -61, -13, -40, 45, -84, 41, 56, -13, 47, -14, 0, 23, -15, 55, -39, 47, 85, 58, 7, -75, -71, 67, -66, -74, -78, -68, 27, 74, 114, -15, 32, 46, 
  -95, -20, 48, -91, 58, -8, -56, -4, -20, -14, -73, -16, -73, -52, -87, -47, 15, -65, -36, 28, -39, 74, -44, 95, -23, -57, -12, -16, -101, -44, 57, -47, -34, -107, 85, 64, -5, -54, -76, -23, -66, 34, -67, 36, -15, -9, 114, 2, -77, -66, -2, -77, 35, -52, 47, -57, -76, -48, -25, 52, -16, -58, -43, 49, 17, -33, 87, -59, -4, 95, 34, 41, 53, -61, -69, 12, 84, 29, -46, 55, 44, 62, 90, 18, 77, 47, 107, 39, 30, 
  15, 66, 7, -51, -31, -16, 37, -17, 53, 62, -72, 72, 63, -18, 20, -30, 7, -71, -62, 44, -39, -68, 65, -88, -19, -14, -70, -60, 47, 79, -56, 28, 77, -55, -5, 30, -85, -1, -10, -33, -73, -77, 32, 78, 25, -66, -87, 27, -12, 15, 26, 33, -87, 22, 37, -52, 64, -56, -38, 98, -66, 60, -87, 17, -48, -32, -38, -84, -74, -68, -71, 80, -8, -10, -19, 31, -88, -89, -98, -57, 55, -23, -16, -94, -30, 27, 70, -21, 14, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,89 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0025507812388241291, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.022733245044946671, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.027658127248287201, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,2 } };
const TfArray<1, float> quant9_scale = { 1, { 0.052889198064804077, } };
const TfArray<1, int> quant9_zero = { 1, { -22 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 89, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1780, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 96), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1022358_32_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022358_32_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022358_32_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022358_32_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022358_32_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
