# ==========================================================
# CONSOLE & LOGGING
# ==========================================================
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y

# Enable Float formatting for printf (Crucial for CSV decimal values)
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_PICOLIBC_IO_FLOAT=y

# ==========================================================
# I2C BUS & PMIC 
# ==========================================================
CONFIG_I2C=y
CONFIG_MFD_NPM13XX=y
CONFIG_REGULATOR=y
CONFIG_REGULATOR_NPM13XX=y

# ==========================================================
# SENSORS
# ==========================================================
CONFIG_SENSOR=y
CONFIG_BMI270=y
CONFIG_ICP201XX=y
CONFIG_SENSOR_ASYNC_API=y