# Console & Logging
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y


# I2C & PMIC
CONFIG_I2C=y
CONFIG_MFD_NPM13XX=y
CONFIG_REGULATOR=y
CONFIG_REGULATOR_NPM13XX=y

# Sensor Subsystem
CONFIG_SENSOR=y
CONFIG_BMI270=y

# Shell Subsystem (Required for SENSOR_SHELL)
CONFIG_SHELL=y
CONFIG_SENSOR_SHELL=y

# GPIO (Callbacks are natively supported, no extra flag needed)
CONFIG_GPIO=y

# Sensor interrupts
CONFIG_SENSOR_ASYNC_API=y

CONFIG_REGULATOR=y