# Logging
CONFIG_LOG=y

# Modem library
CONFIG_NRF_MODEM_LIB=y

# LTE Link Control
CONFIG_LTE_LINK_CONTROL=y
CONFIG_LTE_NETWORK_MODE_LTE_M=y

# Heap and memory
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=2048

# Cristal oscillator stuff for LTE

# Disable the external 32 kHz crystal (LFXO)
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=n

# Use internal RC oscillator instead of external crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y


#other
CONFIG_PWM=y
CONFIG_LED=y
CONFIG_LED_PWM=y

CONFIG_I2C=y
CONFIG_MFD_NPM13XX=y
CONFIG_REGULATOR=y
CONFIG_REGULATOR_NPM13XX=y

