CONFIG_APP_GNSS_POWER_TEST=y
CONFIG_NRF_CLOUD=y
CONFIG_NRF_CLOUD_AGNSS=y
CONFIG_MODEM_INFO=y
CONFIG_MODEM_INFO_ADD_NETWORK=y
CONFIG_MQTT_HELPER_RX_TX_BUFFER_SIZE=2048
CONFIG_MQTT_HELPER_PAYLOAD_BUFFER_LEN=8192