/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1022358_32_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1022358_4[] = { "fall", "no_fall" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1022358_27_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_1022358_27_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1022358_27 = {
    27, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    0.5f, // float scale-axes
    1, // int input-decimation-ratio
    "high", // select filter-type
    3.80859375f, // float filter-cutoff
    6, // int filter-order
    "Wavelet", // select analysis-type
    4096, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    false, // boolean do-fft-overlap
    1, // int wavelet-level
    "rbio3.1", // select wavelet
    false // boolean extra-low-freq
};

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1022358_28_axes[] = { 3 };
const uint32_t ei_dsp_config_1022358_28_axes_size = 1;
ei_dsp_config_flatten_t ei_dsp_config_1022358_28 = {
    28, // uint32_t blockId
    1, // int implementationVersion
    1, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    false, // boolean rms
    true, // boolean stdev
    false, // boolean skewness
    false, // boolean kurtosis
    0 // int moving_avg_num_windows
};

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1022358_31_axes[] = { 4 };
const uint32_t ei_dsp_config_1022358_31_axes_size = 1;
ei_dsp_config_flatten_t ei_dsp_config_1022358_31 = {
    31, // uint32_t blockId
    1, // int implementationVersion
    1, // int length of axes
    1.0f, // float scale-axes
    false, // boolean average
    false, // boolean minimum
    true, // boolean maximum
    false, // boolean rms
    false, // boolean stdev
    false, // boolean skewness
    false, // boolean kurtosis
    0 // int moving_avg_num_windows
};

const float ei_dn_standard_scaler_mean_1022358_27[84] = { 3.2222579943828094, 0.4260009004519536, 0.4224021598314628, -0.09768863960814017, -0.022673301789790202, 0.0232158617877688, 0.09481022281046861, 0.0002594289998720948, 0.00006471201400134491, 0.070817550816215, 0.006307888043430956, 0.07082000938841165, 0.0032266119918905388, 7.104921195675165, 2.923083342649998, 0.534907783758946, 0.5202879003225229, -0.13770064033376864, -0.028325403053485132, 0.02749181226469003, 0.1294115632867966, 0.00011953258422035782, -0.00011609649308621346, 0.12382945811423736, 0.0210230418321981, 0.12386426645784807, 0.033708613413648725, 13.924212849827914, 3.2420554913007296, 0.4628430071549538, 0.4605937950122051, -0.11066719628392886, -0.025359499533974136, 0.025803623718578212, 0.11132380425547943, 0.0002758075281165545, 0.0001362218069347457, 0.08020945775250976, 0.008733231348555703, 0.08021163783537653, 0.07484457795358955, 6.8317047444578165, 3.0178199835312673, 0.5896536212701063, 0.5790373339102819, -0.17971350755542517, -0.037762698789876405, 0.03714177834688319, 0.17715787953959825, -0.00017206322039176787, 0.00023282101764589942, 0.15130142433903157, 0.032013503997437416, 0.1513305140706973, 0.12476193396604429, 10.715183589741205, 3.2886058966318767, 0.44588394287305, 0.4407557375920125, -0.10297424217256215, -0.024373981036627905, 0.024083542182462482, 0.1000592931245382, 0.00032304505581904757, -0.00040658648941200974, 0.07340943424078898, 0.006866585921111086, 0.07341241443481965, -0.09112401727873545, 6.005960604142493, 3.036945701868106, 0.5656770136111822, 0.5529014850274111, -0.15334504688970554, -0.03137916407409088, 0.033021703798126856, 0.14652423420204566, 0.0001090989914345277, -0.000482477258027267, 0.1282408397644758, 0.02202664401012067, 0.12827478630038408, -0.1270572973531671, 10.60210000933745 };
const float ei_dn_standard_scaler_scale_1022358_27[84] = { 1.9408388434217358, 23.083601136389284, 21.568907254541273, 17.915597808310604, 64.15115083004545, 61.96435547322501, 18.03564109162829, 534.924829398437, 1633.2879866981843, 28.42756297505271, 152.2556028408603, 28.427208946031566, 1.3799366995403994, 0.1385978938641832, 1.6828612297515346, 16.83475587891553, 12.74480426867906, 11.016284018421262, 52.47350194250329, 55.39545448516175, 12.441898605596919, 439.2114277765627, 325.64288915045876, 13.478001699791484, 39.18694593572658, 13.476995861269666, 0.56364045836252, 0.09265308937015938, 2.0150405379318594, 20.96969976689714, 18.9210052390122, 13.887208883701215, 50.835042887002075, 51.60575989550218, 13.236549133901867, 387.56105300162653, 1645.7160983368335, 21.209172509693165, 83.77616592450799, 21.208990100570375, 1.2915830683454483, 0.1461596376546587, 1.6550845257554687, 15.925989141004077, 11.567921630365321, 8.163786382783941, 35.64454483372398, 36.51466530532909, 7.76287717996559, 338.8935218454831, 298.7204712284424, 10.635551978784905, 25.015975091630654, 10.634074227782614, 0.8594206314752446, 0.10626372858433024, 2.1647006655625667, 22.064517834790117, 18.805208170848385, 17.710894139604203, 59.664960531475515, 59.47775019867512, 18.912310032131852, 486.0077133488284, 1839.5526991982308, 26.561500744746535, 150.3223796318312, 26.56128242766919, 1.454522091650815, 0.16436241593760323, 1.842774472235929, 16.888859899012495, 12.602672795096169, 10.280454480012384, 42.9449064114778, 41.25007730393651, 10.645020253890914, 355.4807791932982, 313.40178037501414, 13.6237824960536, 42.386755096141634, 13.621626153752546, 0.7806084427997864, 0.11238189515687531 };
const float ei_dn_standard_scaler_var_1022358_27[84] = { 0.26547342266355295, 0.0018766914569997354, 0.0021495310060106387, 0.0031155691252406116, 0.00024299150814294267, 0.00026044506133596603, 0.0030742333631256402, 0.0000034947369056908457, 3.748646297059761e-7, 0.001237430281115194, 0.00004313734717177002, 0.001237461102921156, 0.5251479448167671, 52.05791122225021, 0.3531046117376264, 0.0035284693872952464, 0.006156496825145773, 0.008240048189004237, 0.0003631783091394904, 0.00032587552236016635, 0.006459913228564217, 0.000005183853710337264, 0.000009430110930849167, 0.005504894324432936, 0.00065120415746425, 0.005505716056731711, 3.1477170116719506, 116.48773221263001, 0.24628186000862629, 0.0022741315059624585, 0.0027932614525164614, 0.005185254344737001, 0.0003869667156306144, 0.0003754945562210051, 0.005707559503018736, 0.000006657631381908542, 3.692242059478619e-7, 0.0022230669948636213, 0.00014248168373391415, 0.0022231052342557194, 0.5994532426166431, 46.81069451202028, 0.36505612832915035, 0.0039426404151841985, 0.00747290264710299, 0.015004334428784126, 0.0007870708957025849, 0.0007500070599888427, 0.016594133126868457, 0.000008707098665978269, 0.000011206500854987552, 0.0088405631571519, 0.0015979571465659947, 0.008843020363770599, 1.3539058023769532, 88.55842809500629, 0.21340485655775163, 0.0020540505014674222, 0.0028277675685375236, 0.0031880052325910665, 0.000280906174029493, 0.0002826773002466334, 0.0027958305273185296, 0.000004233637566171356, 2.955122796170368e-7, 0.0014174076790357383, 0.00004425401877584826, 0.0014174309795352113, 0.4726714339658092, 37.016467160561966, 0.29447987848381246, 0.0035058984623728318, 0.006296144379976306, 0.009461835016686338, 0.0005422214308771511, 0.0005876929304335792, 0.008824843570684101, 0.00000791348444637487, 0.000010181155753684484, 0.005387714785667611, 0.0005565954590609263, 0.005389420701940642, 1.641094204169965, 79.17850490161558 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1022358_27 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1022358_27,
    .mean_data_len = 84,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1022358_27,
    .scale_data_len = 84,
    .var_data = (float *)ei_dn_standard_scaler_var_1022358_27,
    .var_data_len = 84
};
ei_data_normalization_t ei_data_normalization_config_1022358_27 = {
    (void *) &ei_data_normalization_standard_scaler_config_1022358_27, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};
const float ei_dn_standard_scaler_mean_1022358_28[4] = { 0.023327020176190837, -0.03255897437771543, 0.07325641060343538, 0.02858887383571038 };
const float ei_dn_standard_scaler_scale_1022358_28[4] = { 23.939255358838043, 32.37462293885582, 13.921710259903538, 47.1173712350733 };
const float ei_dn_standard_scaler_var_1022358_28[4] = { 0.0017449328763553447, 0.0009540926760275871, 0.005159585553951903, 0.0004504409806179442 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1022358_28 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1022358_28,
    .mean_data_len = 4,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1022358_28,
    .scale_data_len = 4,
    .var_data = (float *)ei_dn_standard_scaler_var_1022358_28,
    .var_data_len = 4
};
ei_data_normalization_t ei_data_normalization_config_1022358_28 = {
    (void *) &ei_data_normalization_standard_scaler_config_1022358_28, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};
const float ei_dn_standard_scaler_mean_1022358_31[1] = { 0.03774871808202125 };
const float ei_dn_standard_scaler_scale_1022358_31[1] = { 16.690522510605717 };
const float ei_dn_standard_scaler_var_1022358_31[1] = { 0.0035897163599239034 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1022358_31 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1022358_31,
    .mean_data_len = 1,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1022358_31,
    .scale_data_len = 1,
    .var_data = (float *)ei_dn_standard_scaler_var_1022358_31,
    .var_data_len = 1
};
ei_data_normalization_t ei_data_normalization_config_1022358_31 = {
    (void *) &ei_data_normalization_standard_scaler_config_1022358_31, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1022358_4_size = 3;
ei_model_dsp_t ei_dsp_blocks_1022358_4[ei_dsp_blocks_1022358_4_size] = {
    { // DSP block 27
        27,
        84, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1022358_27, // pointer to config struct
        ei_dsp_config_1022358_27_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1022358_27_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1022358_27, // data normalization config
    },
    { // DSP block 28
        28,
        4, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_1022358_28, // pointer to config struct
        ei_dsp_config_1022358_28_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1022358_28_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_1022358_28, // data normalization config
    },
    { // DSP block 31
        31,
        1, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_1022358_31, // pointer to config struct
        ei_dsp_config_1022358_31_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1022358_31_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_1022358_31, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1022358_32 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1022358_32_init,
    .model_invoke = &tflite_learn_1022358_32_invoke,
    .model_reset = &tflite_learn_1022358_32_reset,
    .model_input = &tflite_learn_1022358_32_input,
    .model_output = &tflite_learn_1022358_32_output,
};

const uint8_t ei_output_tensors_indices_1022358_32[1] = { 0 };
const uint8_t ei_output_tensors_size_1022358_32 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1022358_32 = {
    .implementation_version = 1,
    .block_id = 32,
    .output_tensors_indices = ei_output_tensors_indices_1022358_32,
    .output_tensors_size = ei_output_tensors_size_1022358_32,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1022358_32,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1022358_4_size = 1;
const uint32_t ei_learning_block_1022358_32_inputs[3] = { 27,28,31 };
const uint8_t ei_learning_block_1022358_32_inputs_size = 3;
const ei_learning_block_t ei_learning_blocks_1022358_4[ei_learning_blocks_1022358_4_size] = {
    {
        32,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1022358_32,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1022358_32_inputs,
        ei_learning_block_1022358_32_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1022358_32 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1022358_4_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1022358_4[ei_postprocessing_blocks_1022358_4_size] = {
    {
        .block_id = 32,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1022358_32,
        .input_block_id = 32
    },
};

const uint8_t freeform_outputs_1022358_4_size = 0;

uint32_t *freeform_outputs_1022358_4 = nullptr;

const ei_impulse_t impulse_1022358_4 = {
    .project_id = 1022358,
    .project_owner = "tomasvenda",
    .project_name = "Bracelet Fall Detection",
    .impulse_id = 4,
    .impulse_name = "Impulse #4",
    .deploy_version = 4,

    .nn_input_frame_size = 89,
    .raw_sample_count = 225,
    .raw_samples_per_frame = 5,
    .dsp_input_frame_size = 225 * 5,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_1022358_4_size,
    .dsp_blocks = ei_dsp_blocks_1022358_4,

    .learning_blocks_size = ei_learning_blocks_1022358_4_size,
    .learning_blocks = ei_learning_blocks_1022358_4,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1022358_4_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1022358_4,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "acc_x + acc_y + acc_z + pressure_delta + press_step",
    .slice_size = (225/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_1022358_4,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1022358_4_size,
    .freeform_outputs = freeform_outputs_1022358_4
};

ei_impulse_handle_t impulse_handle_1022358_4 = ei_impulse_handle_t( &impulse_1022358_4 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1022358_4;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1022358_4;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1022358_4_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1022358_4;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
