/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_1022358_14_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1022358_1[] = { "fall", "no_fall" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1022358_12_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_1022358_12_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1022358_12 = {
    12, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    0.5f, // float scale-axes
    1, // int input-decimation-ratio
    "high", // select filter-type
    7.6171875f, // float filter-cutoff
    6, // int filter-order
    "Wavelet", // select analysis-type
    4096, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    false, // boolean do-fft-overlap
    1, // int wavelet-level
    "rbio3.1", // select wavelet
    false // boolean extra-low-freq
};

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1022358_13_axes[] = { 3 };
const uint32_t ei_dsp_config_1022358_13_axes_size = 1;
ei_dsp_config_flatten_t ei_dsp_config_1022358_13 = {
    13, // uint32_t blockId
    1, // int implementationVersion
    1, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    false, // boolean rms
    true, // boolean stdev
    false, // boolean skewness
    false, // boolean kurtosis
    0 // int moving_avg_num_windows
};

const float ei_dn_standard_scaler_mean_1022358_12[84] = { 3.382785556697044, 0.6587240147490462, 0.6517580715047211, -0.07853510409217923, -0.024901115676454668, 0.024614149862078622, 0.08076456054544248, 0.00015352361949461194, 0.000015930380648458732, 0.05442676689679257, 0.003662809810284212, 0.05442851620233234, 0.00939649936377204, 3.618331597546632, 3.2477663444871663, 0.6740933195883486, 0.6545776150056294, -0.18108587751180685, -0.05370256385155523, 0.052892552375668235, 0.189753963025052, 0.0005424918185666937, 0.001174069254658138, 0.1347494129279331, 0.02198696761497711, 0.13482488784156427, 0.1310005151674527, 5.701347414701551, 3.239114517925166, 0.6738721793439207, 0.6661322424892618, -0.039826314242854086, -0.00997370807894216, 0.010114789569648687, 0.039097446478715464, 0.00020512150542439, -0.00001697012656397536, 0.029770565094003658, 0.0011044754155132793, 0.029771150727638928, -0.05476158539257834, 5.080660445200858, 3.090785354626279, 0.6790689948727103, 0.6488279478014016, -0.09733447078771952, -0.02303986983645723, 0.022139098914927106, 0.0932844244100216, 0.0005316723773461024, -0.0008233647159181792, 0.08093818791304566, 0.008406756111927441, 0.08102036136038163, -0.25166656022515743, 8.026262682166044, 3.287332431608889, 0.6758071619923375, 0.6716607667568351, -0.0736086320781595, -0.02106540694738887, 0.021087222462598264, 0.07307232361474708, 0.00041466286943028715, -0.000044305713469673014, 0.05290505604254974, 0.0033628365821366498, 0.05290653824634036, 0.05079373928127388, 4.6602786890037375, 3.1688941697112654, 0.6841552397784065, 0.6675143682656168, -0.18778991354864186, -0.04980469930979634, 0.04731430610477486, 0.18223231299897702, 0.00035450312771969657, -0.0009782214914089652, 0.14003202197055856, 0.023484001149904735, 0.14012107084027858, 0.007229259139819055, 6.614539976850026 };
const float ei_dn_standard_scaler_scale_1022358_12[84] = { 2.6303986994886284, 28.707604414183432, 22.393876137968, 24.52521056694097, 57.161168388338766, 56.47581671486373, 22.96031411221367, 268.038613992125, 1940.2981953401008, 39.15275622942717, 289.9242263368153, 39.15049294801988, 1.628261730237767, 0.22544102003521577, 2.13098610165002, 22.422281626321148, 10.434906291439662, 10.001395203094217, 25.520726625272694, 27.267784098690605, 9.920842542467554, 174.65713640416226, 242.65050008603353, 16.806696343254497, 45.246046578456266, 16.811407240237862, 0.9333943222071325, 0.15390894417407766, 2.1215701009612795, 27.377512080153316, 22.657899514900837, 49.742411819425506, 162.8491869752558, 156.7301534570164, 55.717354490123654, 736.2872521775629, 5432.701363277616, 70.07306066449989, 828.4325379402013, 70.07318101054192, 1.7331723260074312, 0.20174640387709727, 1.9776437500843012, 24.95941574271707, 10.797592174537167, 19.492080512900245, 68.90890378778347, 71.06444422093662, 19.066249863259625, 376.98292714327505, 258.8007176197729, 23.93776178983831, 100.13843408085465, 23.92200522982026, 0.7375352628687264, 0.13214598924690787, 2.1236402288094367, 29.544199259209524, 24.245668914753818, 24.715882533336426, 66.89518326464577, 66.41396624089812, 24.822644311807654, 318.092243490681, 2407.0111276104017, 43.86792906906749, 318.721168527366, 43.867181314960405, 1.7934016053589663, 0.19930496340807405, 1.9334298912288461, 22.780405331198978, 11.424320257301053, 9.865639235376293, 29.159122480973043, 28.678499720553635, 9.918560784528509, 237.4468793724103, 197.30781021805674, 16.745852532973107, 44.47315800740171, 16.74187076034163, 0.8581125464753017, 0.13496996665993521 };
const float ei_dn_standard_scaler_var_1022358_12[84] = { 0.1445296123123551, 0.0012134058762485003, 0.001994074851917917, 0.0016625492156979171, 0.0003060538206401003, 0.0003135270092930663, 0.0018968996202879732, 0.000013918911480098881, 2.6562138723254243e-7, 0.0006523419675258287, 0.00001189682261443388, 0.0006524173931979603, 0.3771825296273143, 19.675877880647338, 0.22021087649117885, 0.001989025696593953, 0.009183810066378544, 0.00999721017768045, 0.0015353731059752115, 0.0013449319373212692, 0.010160214723897871, 0.00003278138732691668, 0.000016983907607186557, 0.0035402610992504966, 0.0004884709305655911, 0.003538277271440608, 1.1478091710822966, 42.21553351440172, 0.22216990400952155, 0.0013341726743505986, 0.0019478733112694908, 0.00040415347987873736, 0.00003770759298065511, 0.00004070941695084417, 0.00032212098979575275, 0.0000018446137319967007, 3.3881945155875236e-8, 0.00020365628897526592, 0.0000014570877390181859, 0.00020365558944352187, 0.33290207959125573, 24.569051782058157, 0.25568419183017166, 0.0016052074619571325, 0.008577212300792156, 0.002631986193751431, 0.00021059561188833568, 0.0001980137152177608, 0.00275086602603944, 0.000007036499084191678, 0.000014930317645392356, 0.001745150629291342, 0.00009972370569878623, 0.001747450321661989, 1.8383763355165261, 57.265364203357095, 0.22173697197738745, 0.0011456594784875207, 0.0017011071078756642, 0.0016369965157011135, 0.00022346540775904666, 0.00022671547548142783, 0.0016229454082820327, 0.000009883114835161018, 1.726011972805167e-7, 0.0005196437818904064, 0.000009844149078959122, 0.000519661497598241, 0.310917302859266, 25.174669130477003, 0.26751192271226654, 0.0019269795493273205, 0.007661949084956557, 0.010274236053582117, 0.001176118549856791, 0.001215870002819975, 0.010164889962119648, 0.0000177364650499669, 0.000025686885311355303, 0.00356603396368491, 0.0005055965025051976, 0.0035677304079062026, 1.3580366677993014, 54.894106276707845 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1022358_12 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1022358_12,
    .mean_data_len = 84,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1022358_12,
    .scale_data_len = 84,
    .var_data = (float *)ei_dn_standard_scaler_var_1022358_12,
    .var_data_len = 84
};
ei_data_normalization_t ei_data_normalization_config_1022358_12 = {
    (void *) &ei_data_normalization_standard_scaler_config_1022358_12, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};
const float ei_dn_standard_scaler_mean_1022358_13[4] = { 0.00025462183942984076, -0.030378150863244253, 0.031092436647653078, 0.005582491167774033 };
const float ei_dn_standard_scaler_scale_1022358_13[4] = { 2473.4068210386567, 29.25597353711134, 27.93819758862689, 228.56015137181265 };
const float ei_dn_standard_scaler_var_1022358_13[4] = { 1.6345902034369225e-7, 0.0011683444261590115, 0.0012811595875851169, 0.000019142513850464153 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1022358_13 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1022358_13,
    .mean_data_len = 4,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1022358_13,
    .scale_data_len = 4,
    .var_data = (float *)ei_dn_standard_scaler_var_1022358_13,
    .var_data_len = 4
};
ei_data_normalization_t ei_data_normalization_config_1022358_13 = {
    (void *) &ei_data_normalization_standard_scaler_config_1022358_13, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1022358_1_size = 2;
ei_model_dsp_t ei_dsp_blocks_1022358_1[ei_dsp_blocks_1022358_1_size] = {
    { // DSP block 12
        12,
        84, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1022358_12, // pointer to config struct
        ei_dsp_config_1022358_12_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1022358_12_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1022358_12, // data normalization config
    },
    { // DSP block 13
        13,
        4, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_1022358_13, // pointer to config struct
        ei_dsp_config_1022358_13_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1022358_13_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_1022358_13, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1022358_14 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1022358_14_init,
    .model_invoke = &tflite_learn_1022358_14_invoke,
    .model_reset = &tflite_learn_1022358_14_reset,
    .model_input = &tflite_learn_1022358_14_input,
    .model_output = &tflite_learn_1022358_14_output,
};

const uint8_t ei_output_tensors_indices_1022358_14[1] = { 0 };
const uint8_t ei_output_tensors_size_1022358_14 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1022358_14 = {
    .implementation_version = 1,
    .block_id = 14,
    .output_tensors_indices = ei_output_tensors_indices_1022358_14,
    .output_tensors_size = ei_output_tensors_size_1022358_14,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1022358_14,
    .dequantize_output = 0,
};

const ei_learning_block_config_anomaly_kmeans_t ei_learning_block_config_1022358_15 = {
    .implementation_version = 1,
    .block_id = 15,
    .anom_axis = ei_classifier_anom_axes_1022358_15,
    .anom_axes_size = 6,
    .anom_clusters = ei_classifier_anom_clusters_1022358_15,
    .anom_cluster_count = 32,
    .anom_scale = ei_classifier_anom_scale_1022358_15,
    .anom_mean = ei_classifier_anom_mean_1022358_15,
};

const uint8_t ei_learning_blocks_1022358_1_size = 2;
const uint32_t ei_learning_block_1022358_14_inputs[2] = { 12,13 };
const uint8_t ei_learning_block_1022358_14_inputs_size = 2;
const uint32_t ei_learning_block_1022358_15_inputs[2] = { 12,13 };
const uint8_t ei_learning_block_1022358_15_inputs_size = 2;
const ei_learning_block_t ei_learning_blocks_1022358_1[ei_learning_blocks_1022358_1_size] = {
    {
        14,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1022358_14,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1022358_14_inputs,
        ei_learning_block_1022358_14_inputs_size,
    },
    {
        15,
        &run_kmeans_anomaly,
        (void*)&ei_learning_block_config_1022358_15,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1022358_15_inputs,
        ei_learning_block_1022358_15_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1022358_14 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1022358_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1022358_1[ei_postprocessing_blocks_1022358_1_size] = {
    {
        .block_id = 14,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1022358_14,
        .input_block_id = 14
    },
};

const uint8_t freeform_outputs_1022358_1_size = 0;

uint32_t *freeform_outputs_1022358_1 = nullptr;

const ei_impulse_t impulse_1022358_1 = {
    .project_id = 1022358,
    .project_owner = "tomasvenda",
    .project_name = "Bracelet Fall Detection",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 2,

    .nn_input_frame_size = 88,
    .raw_sample_count = 150,
    .raw_samples_per_frame = 4,
    .dsp_input_frame_size = 150 * 4,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_1022358_1_size,
    .dsp_blocks = ei_dsp_blocks_1022358_1,

    .learning_blocks_size = ei_learning_blocks_1022358_1_size,
    .learning_blocks = ei_learning_blocks_1022358_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1022358_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1022358_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "acc_x + acc_y + acc_z + pressure_delta",
    .slice_size = (150/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_KMEANS,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_1022358_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1022358_1_size,
    .freeform_outputs = freeform_outputs_1022358_1
};

ei_impulse_handle_t impulse_handle_1022358_1 = ei_impulse_handle_t( &impulse_1022358_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1022358_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1022358_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1022358_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1022358_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
